/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.poc.kafka.avro.model;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class Score extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4188670847227050158L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Score\",\"namespace\":\"org.poc.kafka.avro.model\",\"fields\":[{\"name\":\"subject\",\"type\":\"string\"},{\"name\":\"marks\",\"type\":\"int\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  @Deprecated public java.lang.CharSequence subject;
  @Deprecated public int marks;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>. 
   */
  public Score() {}

  /**
   * All-args constructor.
   */
  public Score(java.lang.CharSequence subject, java.lang.Integer marks) {
    this.subject = subject;
    this.marks = marks;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return subject;
    case 1: return marks;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: subject = (java.lang.CharSequence)value$; break;
    case 1: marks = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'subject' field.
   */
  public java.lang.CharSequence getSubject() {
    return subject;
  }

  /**
   * Sets the value of the 'subject' field.
   * @param value the value to set.
   */
  public void setSubject(java.lang.CharSequence value) {
    this.subject = value;
  }

  /**
   * Gets the value of the 'marks' field.
   */
  public java.lang.Integer getMarks() {
    return marks;
  }

  /**
   * Sets the value of the 'marks' field.
   * @param value the value to set.
   */
  public void setMarks(java.lang.Integer value) {
    this.marks = value;
  }

  /**
   * Creates a new Score RecordBuilder.
   * @return A new Score RecordBuilder
   */
  public static org.poc.kafka.avro.model.Score.Builder newBuilder() {
    return new org.poc.kafka.avro.model.Score.Builder();
  }
  
  /**
   * Creates a new Score RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Score RecordBuilder
   */
  public static org.poc.kafka.avro.model.Score.Builder newBuilder(org.poc.kafka.avro.model.Score.Builder other) {
    return new org.poc.kafka.avro.model.Score.Builder(other);
  }
  
  /**
   * Creates a new Score RecordBuilder by copying an existing Score instance.
   * @param other The existing instance to copy.
   * @return A new Score RecordBuilder
   */
  public static org.poc.kafka.avro.model.Score.Builder newBuilder(org.poc.kafka.avro.model.Score other) {
    return new org.poc.kafka.avro.model.Score.Builder(other);
  }
  
  /**
   * RecordBuilder for Score instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Score>
    implements org.apache.avro.data.RecordBuilder<Score> {

    private java.lang.CharSequence subject;
    private int marks;

    /** Creates a new Builder */
    private Builder() {
      super(org.poc.kafka.avro.model.Score.SCHEMA$);
    }
    
    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(org.poc.kafka.avro.model.Score.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.subject)) {
        this.subject = data().deepCopy(fields()[0].schema(), other.subject);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.marks)) {
        this.marks = data().deepCopy(fields()[1].schema(), other.marks);
        fieldSetFlags()[1] = true;
      }
    }
    
    /**
     * Creates a Builder by copying an existing Score instance
     * @param other The existing instance to copy.
     */
    private Builder(org.poc.kafka.avro.model.Score other) {
            super(org.poc.kafka.avro.model.Score.SCHEMA$);
      if (isValidValue(fields()[0], other.subject)) {
        this.subject = data().deepCopy(fields()[0].schema(), other.subject);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.marks)) {
        this.marks = data().deepCopy(fields()[1].schema(), other.marks);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'subject' field.
      * @return The value.
      */
    public java.lang.CharSequence getSubject() {
      return subject;
    }

    /**
      * Sets the value of the 'subject' field.
      * @param value The value of 'subject'.
      * @return This builder.
      */
    public org.poc.kafka.avro.model.Score.Builder setSubject(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.subject = value;
      fieldSetFlags()[0] = true;
      return this; 
    }

    /**
      * Checks whether the 'subject' field has been set.
      * @return True if the 'subject' field has been set, false otherwise.
      */
    public boolean hasSubject() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'subject' field.
      * @return This builder.
      */
    public org.poc.kafka.avro.model.Score.Builder clearSubject() {
      subject = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'marks' field.
      * @return The value.
      */
    public java.lang.Integer getMarks() {
      return marks;
    }

    /**
      * Sets the value of the 'marks' field.
      * @param value The value of 'marks'.
      * @return This builder.
      */
    public org.poc.kafka.avro.model.Score.Builder setMarks(int value) {
      validate(fields()[1], value);
      this.marks = value;
      fieldSetFlags()[1] = true;
      return this; 
    }

    /**
      * Checks whether the 'marks' field has been set.
      * @return True if the 'marks' field has been set, false otherwise.
      */
    public boolean hasMarks() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'marks' field.
      * @return This builder.
      */
    public org.poc.kafka.avro.model.Score.Builder clearMarks() {
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    public Score build() {
      try {
        Score record = new Score();
        record.subject = fieldSetFlags()[0] ? this.subject : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.marks = fieldSetFlags()[1] ? this.marks : (java.lang.Integer) defaultValue(fields()[1]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  private static final org.apache.avro.io.DatumWriter
    WRITER$ = new org.apache.avro.specific.SpecificDatumWriter(SCHEMA$);  

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, org.apache.avro.specific.SpecificData.getEncoder(out));
  }

  private static final org.apache.avro.io.DatumReader
    READER$ = new org.apache.avro.specific.SpecificDatumReader(SCHEMA$);  

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, org.apache.avro.specific.SpecificData.getDecoder(in));
  }

}
